# Generated by Django 2.0 on 2018-01-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adkar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adkar',
            name='my_date',
        ),
    ]
