# Generated by Django 2.0 on 2018-01-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adkar', '0003_auto_20180116_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='adkar',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
