# Generated by Django 2.0 on 2018-01-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adkar', '0004_adkar_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adkar',
            name='slug',
            field=models.SlugField(null=models.CharField(max_length=200), unique=True),
        ),
    ]
