# Generated by Django 2.0 on 2018-01-17 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adkar', '0005_auto_20180118_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adkar',
            name='slug',
        ),
    ]
