# Generated by Django 2.0 on 2018-01-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adkar', '0007_auto_20180119_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='adkar',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
