# Generated by Django 2.0 on 2018-01-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adkar', '0008_adkar_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adkar',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
