# Generated by Django 2.0 on 2018-01-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adkar', '0009_auto_20180120_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adkar',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
