# Generated by Django 2.0 on 2018-01-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adkar', '0013_auto_20180120_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adkar',
            name='time_of_addition',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='adkar',
            name='time_of_updating',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
