# Generated by Django 2.0 on 2018-02-11 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adkar', '0017_auto_20180206_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adkar',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
