# Generated by Django 2.0 on 2018-06-01 17:31

import adkar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adkar', '0020_auto_20180529_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='adkar',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=adkar.models.upload_location),
        ),
    ]
