# Generated by Django 2.0 on 2018-01-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_stuff', '0002_auto_20180115_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adkar',
        ),
    ]
